version: 2
project_name: hello-world 
builds:
  - main: ./main.go
    binary: hello-world
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^docs:'
  groups:
    - title: "Features"
      regexp: '^feat:'
    - title: "Fixes"
      regexp: '^fix:'
    - title: "Build"
      regexp: '^build:'
    - title: "Continuous Integration"
      regexp: '^ci:'
    - title: "Chores"
      regexp: '^chore:'
    - title: "Style"
      regexp: '^style'
    - title: "Performance"
      regexp: '^perf:'
  use: github

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: osru-leu
    name: dep-demo
    