project_name: hello-world 
builds:
  - main: ./main.go
    binary: hello-world
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64


archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: osru-leu
    name: dep-demo