site_name: Dep Demo
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - API Reference: api-referencel.md

plugins:
  - techdocs-core

markdown_extensions:
  - adomition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: mermaid