apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-github-repos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/osru-leu/dep-demo.git
    path: gitops-crossplane-demo/crossplane-resources
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true