apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mock-composition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XMockResource
  resources:
    - name: mock-deployment
      base:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hello-world
          # namespace: default
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: hello-world
          template:
            metadata:
              labels: 
                app: hello-world
            spec:
              containers:
                - name: hello-world
                  image: nginx:latest
                  ports: 
                    - containerPort: 80
      patches:
        - fromFieldPath: "spec.parameters.replicas"
          toFieldPath: "spec.replicas"
        - fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.namespace"
      readinessChecks:
        - type: MatchString
          fieldPath: status.availableReplicas
          matchString: "2"
  
