apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-repository-template
  title: Create GitHub Repository
  description: Create a new GitHub repository using Crossplane
spec:
  owner: team-platform
  type: service
  parameters:
    - title: Repository Information
      required: ['name', 'description']
      properties:
        name:
          title: Repository Name
          type: string
          description: Name of the repository
        description:
          title: Description
          type: string
          description: A description of the repository
        private:
          title: Private Repository
          type: boolean
          description: Whether the repository should be private
          default: false
        autoInit:
          title: Initialize with README
          type: boolean
          description: Whether to initialize with a README file
          default: true
  steps:
    - id: createRepo
      name: Create GitHub Repository
      action: crossplane:create
      input:
        apiVersion: github.example.org/v1alpha1
        kind: RepoClaim
        metadata:
          generateName: ${{ parameters.name }}-
        spec:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          private: ${{ parameters.private }}
          autoInit: ${{ parameters.autoInit }}
  output:
    links:
      - title: Repository
        url: ${{ steps.createRepo.output.repositoryUrl }}
      - title: Open in GitHub
        icon: github
        url: ${{ steps.createRepo.output.repositoryUrl }} 