name: Go Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Go version
        run: | 
          go version
      
      - name: Install dependencies and tidy
        run: |
          go mod download
          go mod tidy

      - name: Build binary
        run: |
          ./version.sh
          
      - name: Run binary
        run: | 
          ./hello-world
        