name: Release

on: # this is an or not an and
  # push:
  #   tags:
  #     - 'v*'
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      release_bump:
        description: 'Release bump (ignored if version_override is provided)'
        required: true
        default: 'Minor'
        type: choice
        options:
          - Major
          - Minor
          - Patch
      version_override:
        description: 'Optional: manually specify version (e.g., v1.3.0)'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}